### ISSUE TITLE
Add user SSH keys to all servers in the provision_accounts role

### ISSUE THREAD

**Issue by p-j-smith** [UCL-MIRSG/ansible-collection-infra#55]
We could use the [`ansible.posix.authorized_key` module](https://docs.ansible.com/ansible/latest/collections/ansible/posix/authorized_key_module.html#examples) to add our public SSH keys to our accounts, e.g.

```yaml
- name: Set authorized keys taken from url
  ansible.posix.authorized_key:
    user: psmith
    state: present
    key: https://github.com/p-j-smith.keys
```

We would need to add the `key` variable for all users in `os_mirsg_users` in `UCLMedicalImagingEnv`
