### ISSUE TITLE
🐛 [BUG]: Should the `install_container_service` playbook pass when the status is `down`?

### ISSUE THREAD

**Issue by paddyroddy** [UCL-MIRSG/ansible-collection-infra#63]
### Bug Description

In https://github.com/UCL-MIRSG/UCLH-MPBE-SRR-XNAT, I have run `install_xnat` playbook, followed by `install_container_service` playbook. The playbook ends with
```yaml
PLAY RECAP ************************************************************************************************************
xnat_cserv                 : ok=47   changed=3    unreachable=0    failed=0    skipped=7    rescued=0    ignored=0
xnat_web                   : ok=6    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

I would interpret this as passing. However, when I go to the portal I can see
![image](https://github.com/UCL-MIRSG/ansible-collection-infra/assets/15052188/54442cff-5c12-47d2-93f7-be1cf0489e52)
which clearly indicates that it did not work.

From looking at `xnat-cserv` `/storage/xnat/data/xnat/home/logs` I can see an error along the lines of
```
2024-01-25 12:04:09,874 [http-nio-8080-exec-9] ERROR org.nrg.containers.api.DockerControlApi - Failed to list images. jakarta.ws.rs.ProcessingException: java.net.UnknownHostException: xnat-cserv
org.mandas.docker.client.exceptions.DockerException: jakarta.ws.rs.ProcessingException: java.net.UnknownHostException: xnat-cserv
```

Error aside, it begs the question whether the playbook should have some kind of check to see it actually worked. By the time I got `install_xnat` to finish, the portal worked. So naively, I would expect the same here.

### Acceptance Criteria

```[tasklist]
### Related Work Items
```

```[tasklist]
### Tasks
```
